-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS System_user CASCADE;

DROP TABLE IF EXISTS Rental_unit CASCADE;

DROP TABLE IF EXISTS Amenity CASCADE;

DROP TABLE IF EXISTS Amenity_rental_unit CASCADE;

DROP TABLE IF EXISTS Lease CASCADE;

DROP TABLE IF EXISTS Amenity_lease CASCADE;

DROP TABLE IF EXISTS Photo CASCADE;

